services:
  frontend:
    image: node:latest
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
